basket_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "C:/Users/henri/OneDrive/Documents/Codigo/Basketanalysis/basket.duckdb"
      threads: 4                 # (recomendo)
      extensions:
        - httpfs
        - parquet
        - json
      settings:                  # vira PRAGMA/SET dentro do DuckDB
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
