name: basket_dbt
profile: basketanalysis

# aponte para onde as seeds estão de fato
seed-paths: ["basket_dbt/seeds"]
model-paths: ["models"]
macro-paths: ["macros"]

seeds:
  +encoding: utf-8
  +quote_columns: true
  +schema: raw

models:
  +materialized: view
  basket_dbt:
    staging:
      +schema: raw
    enriched:
      +enabled: false        # mantém enriquecidos desligados
      +schema: enriched
